# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  S3_REGION: ${{ secrets.S3_REGION }}
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
  ENCRYPTION_SALT: ${{ secrets.ENCRYPTION_SALT }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  NEIS_KEY: ${{ secrets.NEIS_KEY }}
  MESSAGE_API_KEY: ${{ secrets.MESSAGE_API_KEY }}
  MESSAGE_API_SECRET: ${{ secrets.MESSAGE_API_SECRET }}
  MESSAGE_API_DOMAIN: ${{ secrets.MESSAGE_API_DOMAIN }}
  MESSAGE_FROM: ${{ secrets.MESSAGE_FROM }}
  SCHEDULE_START: ${{ secrets.SCHEDULE_START }}
  SCHEDULE_END: ${{ secrets.SCHEDULE_END }}
  SCHEDULE_ANNOUNCEMENT_OF_FIRST_PASS: ${{ secrets.SCHEDULE_ANNOUNCEMENT_OF_FIRST_PASS }}
  SCHEDULE_ANNOUNCEMENT_OF_SECOND_PASS: ${{ secrets.SCHEDULE_ANNOUNCEMENT_OF_SECOND_PASS }}
  SCHEDULE_CODING_TEST: ${{ secrets.SCHEDULE_CODING_TEST }}
  SCHEDULE_NCS: ${{ secrets.SCHEDULE_NCS }}
  SCHEDULE_DEPTH_INTERVIEW: ${{ secrets.SCHEDULE_DEPTH_INTERVIEW }}
  SCHEDULE_PHYSICAL_EXAMINATION: ${{ secrets.SCHEDULE_PHYSICAL_EXAMINATION }}
  SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_START: ${{ secrets.SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_START }}
  SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_END: ${{ secrets.SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_END }}
  SCHEDULE_MEISTER_TALENT_ENTRANCE_TIME: ${{ secrets.SCHEDULE_MEISTER_TALENT_ENTRANCE_TIME }}
  SCHEDULE_MEISTER_TALENT_EXCLUSION_ENTRANCE_TIME: ${{ secrets.SCHEDULE_MEISTER_TALENT_EXCLUSION_ENTRANCE_TIME }}
  SCHEDULE_ADMISSION_AND_PLEDGE_START: ${{ secrets.SCHEDULE_ADMISSION_AND_PLEDGE_START }}
  SCHEDULE_ADMISSION_AND_PLEDGE_END: ${{ secrets.SCHEDULE_ADMISSION_AND_PLEDGE_END }}
  SCHEDULE_SELECT_FIRST_PASS_CRON: ${{ secrets.SCHEDULE_SELECT_FIRST_PASS_CRON }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6
    - name: Debug ENV Variables
      run: |
        echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" || echo "BUCKET_NAME (null)"
        echo "S3_REGION=${{ secrets.S3_REGION }}" || echo "S3_REGION (null)"
        echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" || echo "S3_ACCESS_KEY (null)"
        echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" || echo "S3_SECRET_KEY (null)"
        echo "ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }}" || echo "ENCRYPTION_PASSWORD (null)"
        echo "ENCRYPTION_SALT=${{ secrets.ENCRYPTION_SALT }}" || echo "ENCRYPTION_SALT (null)"
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" || echo "JWT_SECRET (null)"
        echo "NEIS_KEY=${{ secrets.NEIS_KEY }}" || echo "NEIS_KEY (null)"
        echo "MESSAGE_API_KEY=${{ secrets.MESSAGE_API_KEY }}" || echo "MESSAGE_API_KEY (null)"
        echo "MESSAGE_API_SECRET=${{ secrets.MESSAGE_API_SECRET }}" || echo "MESSAGE_API_SECRET (null)"
        echo "MESSAGE_API_DOMAIN=${{ secrets.MESSAGE_API_DOMAIN }}" || echo "MESSAGE_API_DOMAIN (null)"
        echo "MESSAGE_FROM=${{ secrets.MESSAGE_FROM }}" || echo "MESSAGE_FROM (null)"
        echo "SCHEDULE_START=${{ secrets.SCHEDULE_START }}" || echo "SCHEDULE_START (null)"
        echo "SCHEDULE_END=${{ secrets.SCHEDULE_END }}" || echo "SCHEDULE_END (null)"
        echo "SCHEDULE_ANNOUNCEMENT_OF_FIRST_PASS=${{ secrets.SCHEDULE_ANNOUNCEMENT_OF_FIRST_PASS }}" || echo "SCHEDULE_ANNOUNCEMENT_OF_FIRST_PASS (null)"
        echo "SCHEDULE_ANNOUNCEMENT_OF_SECOND_PASS=${{ secrets.SCHEDULE_ANNOUNCEMENT_OF_SECOND_PASS }}" || echo "SCHEDULE_ANNOUNCEMENT_OF_SECOND_PASS (null)"
        echo "SCHEDULE_CODING_TEST=${{ secrets.SCHEDULE_CODING_TEST }}" || echo "SCHEDULE_CODING_TEST (null)"
        echo "SCHEDULE_NCS=${{ secrets.SCHEDULE_NCS }}" || echo "SCHEDULE_NCS (null)"
        echo "SCHEDULE_DEPTH_INTERVIEW=${{ secrets.SCHEDULE_DEPTH_INTERVIEW }}" || echo "SCHEDULE_DEPTH_INTERVIEW (null)"
        echo "SCHEDULE_PHYSICAL_EXAMINATION=${{ secrets.SCHEDULE_PHYSICAL_EXAMINATION }}" || echo "SCHEDULE_PHYSICAL_EXAMINATION (null)"
        echo "SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_START=${{ secrets.SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_START }}" || echo "SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_START (null)"
        echo "SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_END=${{ secrets.SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_END }}" || echo "SCHEDULE_ENTRANCE_REGISTRATION_PERIOD_END (null)"
        echo "SCHEDULE_MEISTER_TALENT_ENTRANCE_TIME=${{ secrets.SCHEDULE_MEISTER_TALENT_ENTRANCE_TIME }}" || echo "SCHEDULE_MEISTER_TALENT_ENTRANCE_TIME (null)"
        echo "SCHEDULE_MEISTER_TALENT_EXCLUSION_ENTRANCE_TIME=${{ secrets.SCHEDULE_MEISTER_TALENT_EXCLUSION_ENTRANCE_TIME }}" || echo "SCHEDULE_MEISTER_TALENT_EXCLUSION_ENTRANCE_TIME (null)"
        echo "SCHEDULE_ADMISSION_AND_PLEDGE_START=${{ secrets.SCHEDULE_ADMISSION_AND_PLEDGE_START }}" || echo "SCHEDULE_ADMISSION_AND_PLEDGE_START (null)"
        echo "SCHEDULE_ADMISSION_AND_PLEDGE_END=${{ secrets.SCHEDULE_ADMISSION_AND_PLEDGE_END }}" || echo "SCHEDULE_ADMISSION_AND_PLEDGE_END (null)"
        echo "SCHEDULE_SELECT_FIRST_PASS_CRON=${{ secrets.SCHEDULE_SELECT_FIRST_PASS_CRON }}" || echo "SCHEDULE_SELECT_FIRST_PASS_CRON (null)"
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
