# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  cloud.aws.s3.bucket: ${{ secrets.BUCKET_NAME }}
  cloud.aws.region.static: ${{ secrets.S3_REGION }}
  cloud.aws.credentials.access-key: ${{ secrets.S3_ACCESS_KEY }}
  cloud.aws.credentials.secret-key: ${{ secrets.S3_SECRET_KEY }}
  cloud.jasypt.encryptor.key: ${{ secrets.ENCRYPTION_PASSWORD }}
  cloud.jasypt.encryptor.salt: ${{ secrets.ENCRYPTION_SALT }}
  jwt.secret-key: ${{ secrets.JWT_SECRET }}
  neis.key: ${{ secrets.NEIS_KEY }}
  message.api-key: ${{ secrets.MESSAGE_API_KEY }}
  message.api-secret: ${{ secrets.MESSAGE_API_SECRET }}
  message.api-domain: ${{ secrets.MESSAGE_API_DOMAIN }}
  message.from: ${{ secrets.MESSAGE_FROM }}


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      
